"""Admin settings studio, configurable dashboard widgets and site extensions."""

from datetime import datetime, timedelta, timezone
import json
import math
import re
import secrets
from typing import Any, cast

import anvil.server
from anvil.tables import app_tables, query as q

import Core
import AI
import Config
import HisenseCatalogSync


STATE_KEY = "admin_studio_v1"


def _field(key, label, kind, default, hint="", choices=(), core_key=None,
           minimum=None, maximum=None):
  return {
    "key": key, "label": label, "type": kind, "default": default,
    "hint": hint, "choices": list(choices), "core_key": core_key,
    "minimum": minimum, "maximum": maximum
  }


def _text(key, label, default="", hint="", maximum=180, kind="text"):
  return _field(key, label, kind, default, hint, maximum=maximum)


def _toggle(key, label, default=False, hint=""):
  return _field(key, label, "bool", default, hint)


def _number(key, label, default, minimum: Any = 0, maximum: Any = 1000, hint=""):
  return _field(key, label, "number", default, hint,
                minimum=minimum, maximum=maximum)


def _select(key, label, default, choices, hint=""):
  return _field(key, label, "select", default, hint,
                [(label, value) for label, value in choices])


def _core(key, label, kind, default, choices=(), hint=""):
  return _field(key, label, kind, default, hint, choices, core_key=key)


def _section(code, group, title, description, *fields):
  return {
    "id": code, "group": group, "title": title,
    "description": description, "fields": list(fields)
  }


_THEMES = [
  ("01 · GRAPHITE BRUTAL · Чёрная сталь", "graphite"),
  ("02 · CARBON FIRE · Янтарный металл", "carbon-amber"),
  ("03 · CARBON RED · Красный титан", "carbon-red"),
  ("04 · ARCTIC PRO · Светлый лёд", "arctic-light"),
  ("05 · TITANIUM PRO · Светлый металл", "titanium-light")
]
_ON_OFF = [("Включено", "on"), ("Выключено", "off")]
_DENSITY = [("Компактно", "compact"), ("Стандартно", "standard"),
            ("Свободно", "spacious")]


# 107 editable settings sections, organized around the actual site and its
# existing catalogue, CMS, CRM, engineering and user-management features.
SETTINGS_SECTIONS = [
  _section("site.identity", "Сайт", "Профиль сайта",
    "Публичное имя и базовые данные компании.",
    _core("organization_name", "Название компании", "text", "ЭКО-КЛИМАТ"),
    _text("site.tagline", "Короткий слоган", "Климат под инженерным контролем"),
    _text("site.canonical_url", "Основной адрес сайта", "", "Например, https://example.ru", 240, "url")),
  _section("site.contacts", "Сайт", "Контакты",
    "Контакты, которые показываются посетителям сайта.",
    _core("contact_email", "Публичная почта", "text", ""),
    _core("contact_phone", "Телефон", "text", "+79257873848"),
    _core("contact_address", "Адрес", "text", "")),
  _section("site.locale", "Сайт", "Язык и регион",
    "Язык интерфейса и отображение значений.",
    _select("site.locale", "Язык сайта", "ru", [("Русский", "ru"), ("English", "en")]),
    _select("site.date_format", "Формат даты", "dmy", [("ДД.ММ.ГГГГ", "dmy"), ("ГГГГ-ММ-ДД", "ymd")]),
    _select("site.timezone", "Часовой пояс", "Europe/Moscow", [("Москва", "Europe/Moscow"), ("UTC", "UTC") ])),
  _section("site.currency", "Сайт", "Валюта и цены",
    "Валюта по умолчанию и вид цены в карточках.",
    _core("currency", "Валюта сайта", "select", "RUB", [("Рубли · RUB", "RUB"), ("Доллары · USD", "USD"), ("Евро · EUR", "EUR")] ),
    _toggle("pricing.show_from", "Показывать «от» перед ценой", True),
    _toggle("pricing.show_currency", "Показывать обозначение валюты", True)),
  _section("site.appearance", "Сайт", "Оформление сайта",
    "Цветовая тема и визуальная плотность публичной части.",
    _core("site_theme", "Цветовая тема", "select", "graphite", _THEMES),
    _select("site.density", "Плотность блоков", "standard", _DENSITY),
    _toggle("site.motion", "Анимация переходов", True)),
  _section("site.typography", "Сайт", "Типографика",
    "Размеры и начертания для читаемости сайта.",
    _select("site.type_scale", "Размер текста", "normal", [("Компактный", "small"), ("Обычный", "normal"), ("Крупный", "large")]),
    _toggle("site.heading_serif", "Акцентный шрифт заголовков", False)),
  _section("site.header", "Сайт", "Шапка сайта",
    "Управление контактной полосой и быстрыми кнопками.",
    _toggle("header.show_phone", "Показывать телефон в шапке", True),
    _toggle("header.sticky", "Закреплять шапку при прокрутке", False),
    _toggle("header.show_account", "Показывать вход и профиль", True)),
  _section("site.navigation", "Сайт", "Меню сайта",
    "Основные ссылки и поведение меню.",
    _toggle("navigation.catalog", "Показывать каталог", True),
    _toggle("navigation.news", "Показывать новости", True),
    _toggle("navigation.projects", "Показывать проекты авторизованным", True)),
  _section("site.footer", "Сайт", "Подвал сайта",
    "Контакты, подпись и служебные блоки нижней части страниц.",
    _text("footer.caption", "Подпись компании", "КЛИМАТИЧЕСКАЯ ИНЖЕНЕРИЯ"),
    _toggle("footer.show_contacts", "Показывать контакты", True),
    _toggle("footer.show_copyright", "Показывать строку авторских прав", True)),
  _section("site.home.hero", "Сайт", "Главная · первый экран",
    "Заголовок и кнопки главного экрана.",
    _text("home.hero_title", "Заголовок", "Климатические системы с инженерным подходом", maximum=120),
    _text("home.hero_button", "Текст основной кнопки", "Подобрать оборудование", maximum=48),
    _text("home.hero_url", "Адрес основной кнопки", "#catalog", maximum=240)),
  _section("site.home.blocks", "Сайт", "Главная · блоки",
    "Какие информационные блоки показывать на главной.",
    _toggle("home.show_catalog", "Показывать витрину каталога", True),
    _toggle("home.show_gallery", "Показывать галерею работ", True),
    _toggle("home.show_news", "Показывать последние новости", True)),
  _section("site.pages", "Сайт", "Страницы и CMS",
    "Предпочтения редактора страниц и публикаций.",
    _select("cms.default_status", "Статус новой страницы", "draft", [("Черновик", "draft"), ("Опубликована", "published")]),
    _number("cms.preview_width", "Ширина предпросмотра, px", 1180, 640, 1920)),
  _section("site.news", "Сайт", "Новости и статьи",
    "Отображение новостей и карточек публикаций.",
    _number("news.page_size", "Публикаций на странице", 12, 4, 48),
    _toggle("news.show_dates", "Показывать дату публикации", True)),
  _section("site.gallery", "Сайт", "Галерея работ",
    "Вид галереи и число карточек.",
    _number("gallery.page_size", "Карточек на странице", 12, 4, 48),
    _select("gallery.card_ratio", "Формат карточек", "landscape", [("Горизонтальный", "landscape"), ("Квадратный", "square") ])),
  _section("site.seo", "Сайт", "SEO сайта",
    "Общие поисковые заголовки и описание.",
    _text("seo.site_title", "Заголовок по умолчанию", "ЭКО-КЛИМАТ · климатическая инженерия", maximum=160),
    _text("seo.site_description", "Описание сайта", "", maximum=300, kind="textarea"),
    _toggle("seo.include_brand", "Добавлять название компании в заголовки", True)),
  _section("site.seo.catalog", "Сайт", "SEO каталога",
    "Заголовки и индексирование страниц каталога.",
    _text("seo.catalog_title", "Шаблон заголовка каталога", "{category} · оборудование Hisense", maximum=160),
    _toggle("seo.index_catalog", "Разрешить индексацию каталога", True)),
  _section("site.social.preview", "Сайт", "Предпросмотр в соцсетях",
    "Текст и изображение ссылки при публикации.",
    _text("social.og_title", "Заголовок карточки", "ЭКО-КЛИМАТ", maximum=120),
    _text("social.og_description", "Описание карточки", "", maximum=240, kind="textarea")),
  _section("site.urls", "Сайт", "Адреса страниц",
    "Правила ссылок и канонические адреса.",
    _select("urls.trailing_slash", "Завершающий слеш", "keep", [("Сохранять", "keep"), ("Убирать", "remove")]),
    _toggle("urls.canonical", "Использовать основной адрес сайта", True)),
  _section("site.privacy", "Сайт", "Приватность и cookies",
    "Настройки уведомления о cookies и приватности.",
    _toggle("privacy.cookie_notice", "Показывать уведомление о cookies", False),
    _text("privacy.notice_text", "Текст уведомления", "", maximum=300, kind="textarea")),
  _section("catalog.general", "Каталог", "Каталог · общие правила",
    "Видимость и стандартная выдача каталога.",
    _toggle("catalog.public", "Показывать каталог посетителям", True),
    _number("catalog.page_size", "Товаров на странице", 24, 8, 96)),
  _section("catalog.categories", "Каталог", "Категории",
    "Порядок и вид карточек категорий.",
    _select("catalog.category_order", "Сортировка категорий", "manual", [("Вручную", "manual"), ("По алфавиту", "title"), ("По количеству товаров", "products")]),
    _toggle("catalog.hide_empty_categories", "Скрывать пустые категории", True)),
  _section("catalog.cards", "Каталог", "Карточки товаров",
    "Количество элементов и состав карточки каталога.",
    _toggle("catalog.card_show_model", "Показывать модель", True),
    _toggle("catalog.card_show_availability", "Показывать наличие", True),
    _toggle("catalog.card_show_order", "Показывать кнопку заказа", True)),
  _section("catalog.filters", "Каталог", "Фильтры каталога",
    "Включение основных фильтров каталога.",
    _toggle("catalog.filter_category", "Фильтр по категории", True),
    _toggle("catalog.filter_brand", "Фильтр по бренду", True),
    _toggle("catalog.filter_price", "Фильтр по цене", True)),
  _section("catalog.sort", "Каталог", "Сортировка товаров",
    "Доступные способы сортировки списка.",
    _select("catalog.default_sort", "Сортировка по умолчанию", "name", [("По названию", "name"), ("Сначала новые", "newest"), ("Сначала дешевле", "price_asc")]),
    _toggle("catalog.allow_sort_price", "Разрешить сортировку по цене", True)),
  _section("catalog.product.main", "Каталог", "Карточка товара · основное",
    "Поля и порядок основных сведений товара.",
    _toggle("product.show_sku", "Показывать артикул", True),
    _toggle("product.show_brand", "Показывать бренд", True),
    _toggle("product.show_category", "Показывать категорию", True)),
  _section("catalog.product.description", "Каталог", "Карточка товара · описание",
    "Отображение описания и характеристик.",
    _toggle("product.show_description", "Показывать описание", True),
    _toggle("product.show_specs", "Показывать характеристики", True),
    _number("product.spec_limit", "Характеристик в кратком блоке", 8, 1, 30)),
  _section("catalog.product.images", "Каталог", "Изображения товаров",
    "Галерея карточки и подписи изображений.",
    _number("product.gallery_limit", "Изображений в галерее", 12, 1, 30),
    _toggle("product.image_zoom", "Увеличивать главное изображение", True)),
  _section("catalog.stock", "Каталог", "Наличие и склад",
    "Текст и логика отображения остатков.",
    _select("stock.out_of_stock_label", "Подпись при отсутствии", "request", [("Под заказ", "request"), ("Нет в наличии", "none"), ("Уточнить", "ask")]),
    _toggle("stock.show_quantity", "Показывать точное количество", False)),
  _section("catalog.price", "Каталог", "Цены каталога",
    "Формат и доступность цены.",
    _select("price.display_mode", "Вид цены", "exact", [("Точная цена", "exact"), ("По запросу", "request"), ("От минимальной", "from")]),
    _number("price.decimals", "Знаков после запятой", 0, 0, 2)),
  _section("catalog.search", "Каталог", "Поиск по товарам",
    "Минимальная длина запроса и область поиска.",
    _number("search.minimum_length", "Минимум символов", 2, 1, 8),
    _toggle("search.include_sku", "Искать по артикулу", True),
    _toggle("search.include_specs", "Искать по характеристикам", True)),
  _section("catalog.compatibility", "Каталог", "Совместимость оборудования",
    "Настройки таблиц совместимости.",
    _toggle("compatibility.public", "Показывать совместимость посетителям", True),
    _toggle("compatibility.show_confidence", "Показывать уровень проверки", True)),
  _section("catalog.import", "Каталог", "Импорт каталога",
    "Правила проверки и обновления товаров при импорте.",
    _select("import.duplicate_mode", "Совпадающий артикул", "update", [("Обновить товар", "update"), ("Пропустить", "skip"), ("Сообщить об ошибке", "error")]),
    _toggle("import.allow_new_categories", "Создавать новые категории", True)),
  _section("catalog.export", "Каталог", "Экспорт каталога",
    "Формат и объём выгрузок каталога.",
    _select("export.default_format", "Формат по умолчанию", "csv", [("CSV", "csv"), ("JSON", "json")]),
    _toggle("export.include_images", "Включать ссылки на изображения", True)),
  _section("catalog.media", "Каталог", "Медиа-библиотека",
    "Ограничения загрузки и поведение медиа-каталога.",
    _number("media.max_images_per_product", "Изображений на товар", 12, 1, 30),
    _select("media.default_format", "Формат загрузки", "keep", [("Сохранять исходный", "keep"), ("WebP", "webp") ])),
  _section("catalog.brands", "Каталог", "Бренды",
    "Отображение брендов и их сортировка.",
    _select("brands.order", "Порядок брендов", "title", [("По названию", "title"), ("Вручную", "manual")]),
    _toggle("brands.show_logos", "Показывать логотипы брендов", False)),
  _section("orders.general", "Заказы", "Заявки каталога",
    "Приём заявок и обязательность контакта.",
    _toggle("orders.accept_public", "Принимать новые заявки", True),
    _toggle("orders.require_phone", "Запрашивать телефон", True),
    _toggle("orders.require_email", "Запрашивать email", False)),
  _section("orders.statuses", "Заказы", "Статусы обработки",
    "Настройка стандартного статуса и отображения этапов.",
    _select("orders.initial_status", "Статус новой заявки", "new", [("Новая", "new"), ("В обработке", "processing")]),
    _toggle("orders.show_status_public", "Показывать статус клиенту", False)),
  _section("orders.messages", "Заказы", "Сообщения клиенту",
    "Текст подтверждения после отправки заявки.",
    _text("orders.success_title", "Заголовок подтверждения", "Заявка отправлена", maximum=100),
    _text("orders.success_message", "Текст подтверждения", "Мы свяжемся с вами для уточнения деталей.", maximum=300, kind="textarea")),
  _section("orders.routing", "Заказы", "Маршрутизация заявок",
    "Каналы и правила передачи новых заявок.",
    _select("orders.owner_team", "Ответственная группа", "sales", [("Продажи", "sales"), ("Сервис", "service")]),
    _toggle("orders.notify_admin", "Уведомлять администратора", True)),
  _section("forms.leads", "Формы", "Формы заявок",
    "Поля и проверка пользовательских заявок.",
    _toggle("forms.lead_comment", "Поле комментария", True),
    _number("forms.message_limit", "Максимум символов в комментарии", 1200, 100, 5000)),
  _section("forms.contact", "Формы", "Форма контакта",
    "Контактные поля и тексты формы связи.",
    _toggle("forms.contact_email", "Запрашивать email", True),
    _toggle("forms.contact_phone", "Запрашивать телефон", True)),
  _section("forms.validation", "Формы", "Проверка форм",
    "Строгая проверка обязательных полей и сообщений.",
    _toggle("forms.trim_input", "Удалять пробелы по краям", True),
    _text("forms.error_message", "Общий текст ошибки", "Проверьте заполнение полей.", maximum=180)),
  _section("content.blocks", "Контент", "Блоки страниц",
    "Стандартное поведение редактора блоков CMS.",
    _select("content.default_block", "Новый блок", "text", [("Текст", "text"), ("Изображение", "image"), ("Кнопка", "button")]),
    _toggle("content.show_drafts_admin", "Показывать черновики редакторам", True)),
  _section("content.richtext", "Контент", "Редактор текста",
    "Поддерживаемые элементы контента.",
    _toggle("content.rich_links", "Разрешить ссылки", True),
    _toggle("content.rich_tables", "Разрешить таблицы", True),
    _toggle("content.rich_html", "Разрешить ограниченный HTML", False)),
  _section("content.media", "Контент", "Изображения контента",
    "Подписи, размеры и поведение изображений в страницах.",
    _toggle("content.image_alt_required", "Требовать альтернативный текст", True),
    _select("content.image_fit", "Вписывание изображения", "cover", [("Заполнять блок", "cover"), ("Показывать целиком", "contain") ])),
  _section("notifications.center", "Уведомления", "Центр уведомлений",
    "Какие события выводить в панели уведомлений.",
    _toggle("notifications.new_order", "Новые заявки", True),
    _toggle("notifications.import_errors", "Ошибки импорта", True)),
  _section("notifications.email", "Уведомления", "Почтовые уведомления",
    "Адрес и тип писем. Секреты почты хранятся в сервисе Anvil.",
    _text("notifications.email_from", "Публичный адрес отправителя", "", maximum=160),
    _toggle("notifications.email_order", "Письмо о новой заявке", False)),
  _section("notifications.telegram", "Уведомления", "Telegram",
    "Канал для уведомлений о работе каталога.",
    _toggle("notifications.telegram_orders", "Отправлять новые заявки", False),
    _toggle("notifications.telegram_imports", "Отправлять итоги импорта", False)),
  _section("social.links", "Интеграции", "Социальные каналы",
    "Ссылки, которые показываются в публичных блоках.",
    _toggle("social.show_links", "Показывать социальные ссылки", True),
    _select("social.link_style", "Вид ссылок", "icons", [("Иконки", "icons"), ("Текст", "text"), ("Иконки и текст", "both") ])),
  _section("users.registration", "Пользователи", "Регистрация",
    "Поведение создания пользовательских профилей.",
    _toggle("users.public_registration", "Разрешить самостоятельную регистрацию", True),
    _toggle("users.confirm_email", "Требовать подтверждение email", True)),
  _section("users.roles", "Пользователи", "Роли и доступ",
    "Общие настройки назначений ролей.",
    _toggle("users.allow_moderator", "Использовать роль модератора", True),
    _toggle("users.audit_role_changes", "Записывать смену ролей в журнал", True)),
  _section("users.security", "Пользователи", "Безопасность входа",
    "Защитные ограничения пользовательской авторизации.",
    _number("users.session_hours", "Срок сессии, часы", 24, 1, 720),
    _toggle("users.notify_login", "Записывать успешный вход", True)),
  _section("users.profile", "Пользователи", "Профиль пользователя",
    "Дополнительные данные в кабинете пользователя.",
    _toggle("users.profile_phone", "Показывать телефон в профиле", True),
    _toggle("users.profile_company", "Показывать компанию", True)),
  _section("ai.operator", "ИИ и интеграции", "ИИ-помощник",
    "Настройки доступности существующего AI-оператора.",
    _toggle("ai.public_operator", "Показывать помощника на сайте", True),
    _number("ai.reply_limit", "Максимальный размер ответа", 1800, 200, 5000)),
  _section("ai.providers", "ИИ и интеграции", "Поставщики AI",
    "Параметры интерфейса для существующих серверных провайдеров.",
    _toggle("ai.allow_provider_fallback", "Разрешить резервного провайдера", True),
    _toggle("ai.show_provider_status", "Показывать статус провайдера в админке", True)),
  _section("ai.usage", "ИИ и интеграции", "Использование AI",
    "Срок хранения и отображение статистики.",
    _number("ai.history_days", "Дней статистики", 30, 1, 365),
    _toggle("ai.hide_response_logs", "Скрывать содержимое ответов в журналах", True)),
  _section("engineering.projects", "Проекты", "Инженерные проекты",
    "Вид списка проектов и отображение статусов.",
    _select("projects.default_view", "Представление списка", "cards", [("Карточки", "cards"), ("Таблица", "table")]),
    _toggle("projects.show_archived", "Показывать архивные проекты", False)),
  _section("engineering.calculations", "Проекты", "Расчёты",
    "Точность и детализация результатов расчётов.",
    _number("calculations.precision", "Знаков после запятой", 2, 0, 5),
    _toggle("calculations.show_formula", "Показывать применённую формулу", True)),
  _section("engineering.installation.pricing", "Проекты", "Монтаж · цены и тарифы",
    "Редактор тарифов в формате проекта Lovable: валюта и 15 отдельных расценок работ. Материалы и цены товарного каталога остаются в едином редакторе каталога.",
    _core("currency", "Валюта цен", "select", "RUB", [("Рубли · RUB", "RUB"), ("Доллары · USD", "USD"), ("Евро · EUR", "EUR")]),
    _number("installation.pricing.acStandard", "Стандартный монтаж кондиционера, ₽", 8500, 0, 10000000),
    _number("installation.pricing.acPremium", "Сложный монтаж кондиционера, ₽", 12000, 0, 10000000),
    _number("installation.pricing.vrfMainRoute", "Магистраль VRV/VRF, ₽/м", 2800, 0, 1000000),
    _number("installation.pricing.vrfBranch", "Ответвление VRV/VRF, ₽", 4200, 0, 10000000),
    _number("installation.pricing.outdoorUnit", "Монтаж наружного блока, ₽", 6500, 0, 10000000),
    _number("installation.pricing.indoorUnit", "Монтаж внутреннего блока, ₽", 3500, 0, 10000000),
    _number("installation.pricing.commissioning", "Пусконаладка, ₽", 6500, 0, 10000000),
    _number("installation.pricing.pressureTest", "Опрессовка азотом, ₽", 3200, 0, 10000000),
    _number("installation.pricing.vacuum", "Вакуумирование, ₽", 1800, 0, 10000000),
    _number("installation.pricing.refrigerantCharge", "Дозаправка хладагентом, ₽/кг", 1200, 0, 1000000),
    _number("installation.pricing.electricalConnection", "Электрическое подключение, ₽", 2800, 0, 10000000),
    _number("installation.pricing.condensatePumpInstall", "Монтаж дренажной помпы, ₽", 4500, 0, 10000000),
    _number("installation.pricing.coreDrilling", "Алмазное бурение / проходка, ₽", 1800, 0, 10000000),
    _number("installation.pricing.liftHour", "Подъёмник / автовышка · час, ₽", 6500, 0, 10000000),
    _number("installation.pricing.scaffoldShift", "Леса / высота · смена, ₽", 4200, 0, 10000000)),
  _section("engineering.installation", "Проекты", "Монтажные расчёты",
    "Отображение состава монтажной сметы.",
    _toggle("installation.show_materials", "Показывать материалы", True),
    _toggle("installation.show_labor", "Показывать работы", True)),
  _section("crm.clients", "Рабочие процессы", "Клиенты CRM",
    "Представление списка и обязательность данных клиента.",
    _select("crm.client_view", "Вид списка клиентов", "table", [("Таблица", "table"), ("Карточки", "cards")]),
    _toggle("crm.require_contact", "Требовать контакт для клиента", False)),
  _section("crm.tasks", "Рабочие процессы", "Задачи CRM",
    "Приоритеты и отображение задач.",
    _select("crm.task_default_priority", "Приоритет новой задачи", "normal", [("Обычный", "normal"), ("Высокий", "high"), ("Срочный", "urgent")]),
    _toggle("crm.show_completed", "Показывать завершённые задачи", True)),
  _section("crm.service", "Рабочие процессы", "Сервис и обслуживание",
    "Сроки и статусы сервисных записей.",
    _number("service.reminder_days", "Напоминать за дней", 3, 0, 30),
    _toggle("service.show_history", "Показывать историю обслуживания", True)),
  _section("crm.quotes", "Рабочие процессы", "Коммерческие предложения",
    "Срок действия и представление предложений.",
    _number("quotes.validity_days", "Срок действия, дней", 14, 1, 180),
    _toggle("quotes.show_vat", "Показывать НДС отдельной строкой", False)),
  _section("import.defaults", "Импорт и экспорт", "Импорт · сопоставление",
    "Настройки сопоставления входных полей.",
    _toggle("import.match_sku_first", "Сопоставлять товары сначала по артикулу", True),
    _toggle("import.keep_unmapped", "Сохранять неизвестные поля в отчёте", True)),
  _section("import.review", "Импорт и экспорт", "Импорт · проверка",
    "Параметры предпросмотра и обработки ошибочных строк.",
    _number("import.preview_rows", "Строк в предпросмотре", 50, 5, 250),
    _select("import.error_mode", "Ошибочные строки", "skip", [("Пропустить", "skip"), ("Остановить импорт", "stop")])),
  _section("backup.policy", "Импорт и экспорт", "Резервные копии",
    "Параметры ручного резервного копирования.",
    _toggle("backup.include_media", "Включать метаданные медиа", True),
    _number("backup.retention_count", "Хранить копий, шт.", 10, 1, 100)),
  _section("audit.policy", "Система", "Журнал действий",
    "Состав и представление журнала администратора.",
    _number("audit.rows_per_page", "Событий на странице", 40, 10, 200),
    _toggle("audit.include_settings", "Записывать изменения настроек", True)),
  _section("dashboard.widgets", "Система", "Виджеты Dashboard",
    "Выбор блоков и их размера на рабочем столе.",
    _number("dashboard.max_columns", "Колонок на широком экране", 4, 1, 6),
    _select("dashboard.density", "Размер карточек", "standard", _DENSITY)),
  _section("system.health", "Система", "Диагностика",
    "Частота проверки и отображение предупреждений.",
    _toggle("system.show_health", "Показывать состояние модулей", True),
    _toggle("system.show_schema_warnings", "Показывать предупреждения схемы", True)),
  _section("system.performance", "Система", "Производительность",
    "Размер списков и интенсивность обновления.",
    _number("system.page_size", "Размер списков по умолчанию", 50, 10, 200),
    _select("system.refresh_interval", "Интервал обновления", "manual", [("Вручную", "manual"), ("30 секунд", "30"), ("1 минута", "60") ])),
  _section("system.integrations", "Система", "Подключения",
    "Состояние интеграций и видимость подключения.",
    _toggle("integrations.show_status", "Показывать состояние интеграций", True),
    _toggle("integrations.allow_external_links", "Разрешить внешние ссылки", True)),
  _section("system.extensions", "Система", "Плагины и расширения",
    "Управление собственными браузерными модулями CSS и JavaScript.",
    _toggle("extensions.allow_css", "Разрешить CSS-модули", True),
    _toggle("extensions.allow_javascript", "Разрешить JavaScript-модули", True)),
  _section("system.modules", "Система", "Модули проекта",
    "Состав модулей, подключённых к текущему проекту.",
    _select("modules.default_visibility", "Видимость новых модулей", "admin", [("Только администратор", "admin"), ("Все сотрудники", "staff")]),
    _toggle("modules.audit_changes", "Записывать включение и выключение модулей", True)),
  _section("system.ui", "Система", "Интерфейс админки",
    "Плотность панели, подписи и поведение редакторов.",
    _select("admin.density", "Плотность интерфейса", "standard", _DENSITY),
    _toggle("admin.confirm_deletions", "Подтверждать удаление", True)),
  _section("system.search", "Система", "Поиск по проекту",
    "Области поиска и количество результатов.",
    _number("admin.search_limit", "Результатов на раздел", 10, 3, 50),
    _toggle("admin.search_products", "Искать товары", True)),
  _section("system.accessibility", "Система", "Доступность интерфейса",
    "Контрастность, клавиатурная навигация и подписи.",
    _toggle("admin.high_contrast", "Повышенный контраст", False),
    _toggle("admin.focus_outlines", "Показывать фокус клавиатуры", True)),
  _section("system.localization", "Система", "Язык админки",
    "Формат чисел и подписей рабочей области.",
    _select("admin.language", "Язык панели", "ru", [("Русский", "ru"), ("English", "en")]),
    _toggle("admin.compact_dates", "Короткий формат дат", True)),
  _section("system.danger", "Система", "Опасные операции",
    "Дополнительные ограничения для массовых действий.",
    _toggle("system.confirm_bulk", "Подтверждать массовые операции", True),
    _toggle("system.require_reason", "Запрашивать причину удаления", False)),
  _section("system.custom", "Система", "Пользовательские настройки",
    "Значения расширений проекта и пользовательских модулей.",
    _text("custom.module_namespace", "Пространство имён модулей", "eco", "Только латинские буквы, цифры и дефис.", 40),
    _toggle("custom.show_disabled", "Показывать отключённые модули", True)),
  _section("site.maintenance", "Сайт", "Режим обслуживания",
    "Переключатель технического режима и пояснение посетителям.",
    _toggle("site.maintenance_mode", "Включить режим обслуживания", False),
    _text("site.maintenance_message", "Сообщение посетителям", "Сайт временно обновляется.", maximum=240)),
  _section("site.accessibility", "Сайт", "Доступность сайта",
    "Подписи изображений и увеличение интерактивных элементов.",
    _toggle("site.accessible_alt", "Проверять подписи изображений", True),
    _select("site.accessible_scale", "Размер интерфейса", "normal", [("Обычный", "normal"), ("Увеличенный", "large") ])),
  _section("catalog.related", "Каталог", "Связанные товары",
    "Количество и вид рекомендаций в карточке товара.",
    _number("product.related_limit", "Связанных товаров", 4, 0, 12),
    _toggle("product.related_same_category", "Сначала та же категория", True)),
  _section("catalog.archive", "Каталог", "Архив товаров",
    "Отображение неактивных позиций в рабочих списках.",
    _toggle("catalog.show_inactive_admin", "Показывать неактивные в админке", True),
    _toggle("catalog.allow_restore", "Разрешить восстановление товара", True)),
  _section("orders.retention", "Заказы", "История заявок",
    "Сроки хранения и доступ к завершённым заявкам.",
    _number("orders.history_days", "Период истории, дней", 365, 30, 3650),
    _toggle("orders.show_closed", "Показывать закрытые по умолчанию", False)),
  _section("content.preview", "Контент", "Предпросмотр публикаций",
    "Режим предварительного просмотра страниц и публикаций.",
    _select("content.preview_mode", "Режим предпросмотра", "desktop", [("Компьютер", "desktop"), ("Телефон", "mobile")]),
    _toggle("content.preview_show_drafts", "Разрешить предпросмотр черновиков", True)),
  _section("media.policy", "Каталог", "Правила медиа",
    "Максимальный размер изображения для ручной загрузки и импорта.",
    _number("media.max_size_mb", "Максимальный размер, МБ", 12, 1, 40)),
  _section("integrations.webhooks", "Интеграции", "Веб-подключения",
    "Общие параметры внешних адресов и обработчиков.",
    _toggle("integrations.webhook_enabled", "Разрешить существующие обработчики", True),
    _number("integrations.timeout_seconds", "Тайм-аут, сек.", 10, 2, 60)),
  _section("integrations.api", "Интеграции", "API и внешние сервисы",
    "Главный переключатель публичного API проекта. Адреса моделей, ключи и параметры подключений редактируются в разделе «Провайдеры и ключи».",
    _toggle("api.enabled", "Включить внешний API проекта", True)),
  _section("integrations.media.storage", "Интеграции", "Хранилище изображений",
    "Определяет, куда отправляются изображения из PDF/XLSX и каталога. Ключи хранятся только на сервере.",
    _select("media.storage_primary", "Основное хранилище", "auto", [
      ("Автоматически · Cloudinary → ImageKit", "auto"),
      ("Cloudinary", "cloudinary"), ("ImageKit", "imagekit"),
      ("Не загружать во внешнее облако", "none")
    ]),
    _select("media.storage_fallback", "Резервное хранилище", "imagekit", [
      ("ImageKit", "imagekit"), ("Cloudinary", "cloudinary"),
      ("Без резерва", "none")
    ]),
    _toggle("media.external_uploads", "Загружать изображения во внешнее облако", True),
    _toggle("media.dedupe_by_checksum", "Не загружать одинаковые файлы повторно", True),
    _number("media.upload_retries", "Повторов загрузки", 2, 0, 5),
    _text("media.folder_prefix", "Папка в облаке", "catalog/imports", maximum=80)),
  _section("ventilation.page", "Вентиляция", "Вентиляция · страница и SEO",
    "Тексты, видимость блоков и SEO отдельной страницы расчёта вентиляции.",
    _text("ventilation.page_title", "Заголовок страницы", "Расчёт вентиляции", maximum=160),
    _text("ventilation.page_description", "Описание страницы", "Предварительный расчёт стоимости оборудования и монтажа вентиляции.", maximum=400),
    _text("ventilation.seo_title", "SEO Title", "Расчёт вентиляции · оборудование и монтаж", maximum=160),
    _text("ventilation.seo_description", "SEO Description", "Рассчитайте воздухообмен, оборудование и ориентировочную стоимость монтажа вентиляции.", maximum=300),
    _text("ventilation.seo_keywords", "SEO Keywords", "вентиляция, расчёт вентиляции, монтаж вентиляции, воздуховоды", maximum=300),
    _text("ventilation.primary_button", "Текст основной кнопки", "Рассчитать стоимость", maximum=80),
    _toggle("ventilation.show_types", "Показывать виды вентиляции", True),
    _toggle("ventilation.show_process", "Показывать этапы монтажа", True),
    _toggle("ventilation.show_faq", "Показывать FAQ", True),
    _toggle("ventilation.show_media", "Показывать изображения", True)),
  _section("ventilation.fields", "Вентиляция", "Вентиляция · поля и ограничения",
    "Подписи, единицы, обязательность, порядок и допустимые значения исходных данных. Дополнительные поля добавляются JSON-списком в разделе «Пользовательские поля».",
    _text("ventilation.label_area", "Подпись площади", "Площадь помещения", maximum=100),
    _text("ventilation.label_length", "Подпись длины", "Длина помещения", maximum=100),
    _text("ventilation.label_width", "Подпись ширины", "Ширина помещения", maximum=100),
    _text("ventilation.label_height", "Подпись высоты", "Высота потолка", maximum=100),
    _text("ventilation.label_people", "Подпись людей", "Количество людей", maximum=100),
    _text("ventilation.label_duct_length", "Подпись длины воздуховодов", "Длина воздуховодов", maximum=120),
    _text("ventilation.label_branches", "Подпись ответвлений", "Количество ответвлений", maximum=120),
    _select("ventilation.unit_area", "Единица площади", "м²", [("м²", "м²"), ("ft²", "ft²")]),
    _select("ventilation.unit_volume", "Единица объёма", "м³", [("м³", "м³"), ("ft³", "ft³")]),
    _select("ventilation.unit_flow", "Единица расхода", "м³/ч", [("м³/ч", "м³/ч"), ("л/с", "л/с")]),
    _number("ventilation.area_min", "Минимальная площадь", 10, 0.1, 100000),
    _number("ventilation.area_max", "Максимальная площадь", 5000, 1, 1000000),
    _number("ventilation.height_min", "Минимальная высота", 2, 0.5, 30),
    _number("ventilation.height_max", "Максимальная высота", 7, 1, 100),
    _number("ventilation.people_min", "Минимум людей", 1, 0, 100000),
    _number("ventilation.people_max", "Максимум людей", 5000, 1, 1000000),
    _number("ventilation.default_area", "Площадь по умолчанию", 120, 0.1, 100000),
    _number("ventilation.default_height", "Высота по умолчанию", 2.75, 0.5, 30),
    _number("ventilation.default_people", "Людей по умолчанию", 25, 0, 100000)),
  _section("ventilation.rules", "Вентиляция", "Вентиляция · формулы и коэффициенты",
    "Числовые нормы и правила расчёта. Изменения применяются сервером без изменения программного кода.",
    _number("ventilation.people_airflow", "Расход на человека, м³/ч", 40, 0, 1000),
    _number("ventilation.default_air_changes", "Кратность по умолчанию, 1/ч", 2.5, 0, 50),
    _number("ventilation.supply_factor", "Поправка притока", 1.0, 0, 10),
    _number("ventilation.exhaust_factor", "Поправка вытяжки", 1.0, 0, 10),
    _number("ventilation.fan_reserve_percent", "Резерв производительности, %", 15, 0, 200),
    _number("ventilation.duct_velocity", "Скорость в воздуховоде, м/с", 4, 0.1, 30),
    _number("ventilation.rounding_step", "Шаг округления цены, ₽", 10, 1, 100000),
    _number("ventilation.duct_rounding_step", "Шаг округления размера, мм", 5, 1, 100),
    _number("ventilation.heat_capacity", "Коэффициент тепла", 0.335, 0, 10),
    _number("ventilation.recovery_default", "Рекуперация по умолчанию, %", 70, 0, 100),
    _number("ventilation.cooling_capacity_per_unit", "Холодопроизводительность одного блока, кВт", 8, 0.1, 1000),
    _text("ventilation.formula_notes", "Пояснение формул", "V = S × H; Q = max(V × n, N × q); сечение = Q / (3600 × v).", maximum=600)),
  _section("ventilation.prices", "Вентиляция", "Вентиляция · цены и тарифы",
    "Все цены предварительной сметы редактируются здесь. Валюта — рубли; значения не используются другими калькуляторами.",
    _number("ventilation.price_equipment_base", "Базовая стоимость оборудования, ₽", 20000, 0, 100000000),
    _number("ventilation.price_automation", "Автоматика и электрика, ₽", 40000, 0, 100000000),
    _number("ventilation.price_ducts_m2", "Воздуховоды за погонный метр, ₽", 155, 0, 1000000),
    _number("ventilation.price_grille", "Одна решётка, ₽", 480, 0, 1000000),
    _number("ventilation.price_diffuser", "Один диффузор, ₽", 650, 0, 1000000),
    _number("ventilation.price_fan", "Один вентилятор, ₽", 18000, 0, 100000000),
    _number("ventilation.price_recovery", "Рекуператор, ₽", 85000, 0, 100000000),
    _number("ventilation.price_filter", "Фильтр, ₽", 6500, 0, 10000000),
    _number("ventilation.price_silencer", "Шумоглушитель, ₽", 8500, 0, 10000000),
    _number("ventilation.price_valve", "Клапан, ₽", 3200, 0, 10000000),
    _number("ventilation.price_cooling", "Охлаждающий блок, ₽", 45000, 0, 100000000),
    _number("ventilation.price_materials_percent", "Расходные материалы, %", 15, 0, 100),
    _number("ventilation.installation_percent", "Монтаж оборудования, %", 50, 0, 300),
    _number("ventilation.duct_installation_percent", "Монтаж воздуховодов, %", 80, 0, 300),
    _number("ventilation.commissioning_percent", "Пусконаладка, % от монтажа", 10, 0, 100),
    _number("ventilation.additional_percent", "Дополнительные расходы, %", 3, 0, 100)),
  _section("ventilation.types", "Вентиляция", "Вентиляция · типы и оборудование",
    "Добавляйте, отключайте и редактируйте типы помещений и систем через JSON. Поля name, code, air_changes и factor обязательны для расчёта.",
    _text("ventilation.room_types_json", "Типы помещений · JSON", '[{"code":"office","name":"Офисы","air_changes":2.5,"factor":1.5},{"code":"shop","name":"Магазины и ТЦ","air_changes":1.5,"factor":1.2},{"code":"production","name":"Производства","air_changes":2.5,"factor":1.0},{"code":"residential","name":"Квартиры и дома","air_changes":2.0,"factor":1.5}]', maximum=12000, kind="textarea"),
    _text("ventilation.system_types_json", "Типы вентиляции · JSON", '[{"code":"supply_exhaust","name":"Приточно-вытяжная","description":"Одновременно подаёт и удаляет воздух, поддерживая баланс потоков.","mode":"balanced","share":1.0,"enabled":true,"features":[]},{"code":"supply","name":"Приточная","description":"Подаёт наружный воздух с фильтрацией и подготовкой по проекту.","mode":"supply","share":0.6,"enabled":true,"features":[]},{"code":"exhaust","name":"Вытяжная","description":"Удаляет загрязнённый воздух, запахи и избыток влаги.","mode":"exhaust","share":0.4,"enabled":true,"features":[]},{"code":"recovery","name":"С рекуперацией","description":"Передаёт тепло удаляемого воздуха приточному потоку.","mode":"balanced","share":1.0,"enabled":true,"features":["recovery"]},{"code":"cooling","name":"С охлаждением","description":"Добавляет охлаждающий блок в предварительную смету системы.","mode":"balanced","share":1.0,"enabled":true,"features":["cooling"]}]', maximum=12000, kind="textarea"),
    _text("ventilation.equipment_json", "Оборудование · JSON", '[{"code":"fan","name":"Вентилятор","price_key":"ventilation.price_fan","enabled":true},{"code":"recovery","name":"Рекуператор","price_key":"ventilation.price_recovery","enabled":true},{"code":"cooling","name":"Охлаждающий блок","price_key":"ventilation.price_cooling","enabled":true},{"code":"filter","name":"Фильтр","price_key":"ventilation.price_filter","enabled":true},{"code":"silencer","name":"Шумоглушитель","price_key":"ventilation.price_silencer","enabled":true},{"code":"valve","name":"Клапан","price_key":"ventilation.price_valve","enabled":true},{"code":"grille","name":"Решётка","price_key":"ventilation.price_grille","enabled":true},{"code":"diffuser","name":"Диффузор","price_key":"ventilation.price_diffuser","enabled":true},{"code":"automation","name":"Автоматика","price_key":"ventilation.price_automation","enabled":true}]', maximum=12000, kind="textarea"),
    _text("ventilation.custom_fields_json", "Пользовательские поля · JSON", '[]', maximum=12000, kind="textarea"),
    _text("ventilation.custom_units_json", "Пользовательские единицы · JSON", '[]', maximum=8000, kind="textarea")),
  _section("ventilation.results", "Вентиляция", "Вентиляция · результаты и порядок",
    "Управляйте подписями, единицами, видимостью и порядком карточек. Итоговая стоимость всегда выделяется вверху страницы.",
    _text("ventilation.result_schema_json", "Схема результатов · JSON", '[{"key":"volume","label":"Объём помещения","unit":"м³","visible":true,"order":10},{"key":"air_exchange","label":"Необходимый воздухообмен","unit":"м³/ч","visible":true,"order":20},{"key":"supply","label":"Приточный расход","unit":"м³/ч","visible":true,"order":30},{"key":"exhaust","label":"Вытяжной расход","unit":"м³/ч","visible":true,"order":40},{"key":"fan","label":"Производительность установки","unit":"м³/ч","visible":true,"order":50},{"key":"cooling_capacity","label":"Расчётная холодопроизводительность","unit":"кВт","visible":true,"order":55},{"key":"recovery_power","label":"Тепловая мощность рекуперации","unit":"кВт","visible":true,"order":57},{"key":"duct","label":"Сечение воздуховода","unit":"мм","visible":true,"order":60},{"key":"equipment_cost","label":"Оборудование","unit":"₽","visible":true,"order":70},{"key":"installation_cost","label":"Монтаж","unit":"₽","visible":true,"order":80},{"key":"additional_cost","label":"Дополнительные расходы","unit":"₽","visible":true,"order":85},{"key":"total","label":"Итого","unit":"₽","visible":true,"order":90}]', maximum=16000, kind="textarea"),
    _toggle("ventilation.show_breakdown", "Показывать расшифровку", True),
    _toggle("ventilation.show_prices", "Показывать цены по строкам", True),
    _toggle("ventilation.show_units", "Показывать единицы измерения", True)),
  _section("ventilation.content", "Вентиляция", "Вентиляция · тексты и FAQ",
    "Редактируйте блоки страницы, преимущества, этапы и вопросы без изменения кода.",
    _text("ventilation.advantages_json", "Преимущества · JSON", '[{"title":"Расчёт по параметрам объекта","text":"Учитываются площадь, высота, люди и выбранный тип системы."},{"title":"Прозрачная смета","text":"Оборудование, воздуховоды, монтаж и дополнительные расходы показаны отдельно."}]', maximum=12000, kind="textarea"),
    _text("ventilation.process_json", "Этапы работ · JSON", '[{"title":"Осмотр","text":"Уточнение назначения зон и ограничений объекта."},{"title":"Проектирование","text":"Подбор оборудования и трасс по расчётным расходам."},{"title":"Монтаж и запуск","text":"Установка, автоматика, проверка и наладка."}]', maximum=12000, kind="textarea"),
    _text("ventilation.faq_json", "FAQ · JSON", '[{"question":"Что входит в систему вентиляции?","answer":"Оборудование, фильтры, автоматика, воздуховоды и воздухораспределители по проекту."},{"question":"Почему цена уточняется после обследования?","answer":"На итог влияют трассы, проходки, высотные работы, шумовые требования и строительная готовность."}]', maximum=12000, kind="textarea"),
    _text("ventilation.images_json", "Изображения страницы · JSON", '[]', maximum=12000, kind="textarea")),
  _section("ai.models", "ИИ и интеграции", "Модели и режимы AI",
    "Выбор поведения AI Studio и импорта. Конкретные API, модели и ключи редактируются в разделе «Настроить модели и API».",
    _select("ai.default_slot", "Основная модель", "primary", [
      ("Основной провайдер", "primary"), ("Резервный 1", "secondary"),
      ("Резервный 2", "third"), ("Локальная модель", "local")
    ]),
    _select("ai.fallback_slot", "Резервная модель", "secondary", [
      ("Резервный 1", "secondary"), ("Резервный 2", "third"),
      ("Основной провайдер", "primary"), ("Без резерва", "none")
    ]),
    _toggle("ai.vision_enabled", "Разрешить анализ изображений", True),
    _toggle("ai.catalog_drafts", "Разрешить черновики каталога", True),
    _toggle("ai.pdf_ocr", "Использовать AI/OCR для PDF", True),
    _number("ai.max_request_seconds", "Максимальное время запроса, сек.", 30, 5, 120)),
  _section("projects.objects", "Проекты", "Объекты и помещения",
    "Представление инженерных объектов и помещений.",
    _toggle("projects.show_objects", "Показывать объекты", True),
    _toggle("projects.show_rooms", "Показывать помещения", True)),
  _section("projects.systems", "Проекты", "Системы и оборудование",
    "Состав карточек систем и узлов.",
    _toggle("projects.show_components", "Показывать компоненты системы", True),
    _toggle("projects.show_connections", "Показывать связи оборудования", True)),
  _section("operations.estimates", "Рабочие процессы", "Сметы и предложения",
    "Формат и точность сметных значений.",
    _number("estimates.precision", "Знаков после запятой", 2, 0, 4),
    _toggle("estimates.show_source", "Показывать источник цены", True)),
  _section("operations.service", "Рабочие процессы", "Сервисные заявки",
    "Сроки и видимость обслуживания.",
    _number("service.default_reminder", "Напоминание, дней", 3, 0, 60),
    _toggle("service.show_status_public", "Показывать статус заявки клиенту", False)),
  _section("security.permissions", "Пользователи", "Права доступа",
    "Поведение проверки прав в интерфейсе управления.",
    _toggle("security.hide_forbidden_sections", "Скрывать разделы без прав", True),
    _toggle("security.audit_denied_actions", "Записывать отказанные действия", True)),
  _section("security.sessions", "Пользователи", "Сессии пользователей",
    "Отображение сеансов в пользовательском профиле.",
    _toggle("security.show_last_login", "Показывать дату последнего входа", True),
    _number("security.max_sessions", "Сеансов пользователя", 5, 1, 20)),
  _section("system.updates", "Система", "Версия и обновления",
    "Информация о версии и диагностике обновлений.",
    _toggle("system.show_version", "Показывать версию приложения", True),
    _toggle("system.update_notices", "Показывать сообщения об обновлении", True)),
  _section("system.data", "Система", "Работа с данными",
    "Настройки списков, предпросмотра и действий с данными.",
    _number("system.data_preview_limit", "Строк в предпросмотре", 100, 10, 500),
    _toggle("system.data_confirm_overwrite", "Подтверждать перезапись данных", True)),
  _section("system.widgets", "Система", "Виджеты и рабочий стол",
    "Дополнительные параметры выбранных виджетов.",
    _toggle("dashboard.show_empty", "Показывать виджеты с нулевыми значениями", False),
    _toggle("dashboard.show_descriptions", "Показывать пояснения виджетов", True)),
  _section("system.extensions.safety", "Система", "Безопасность расширений",
    "Ограничения размера и публичности браузерных расширений.",
    _number("extensions.max_active", "Активных расширений", 12, 1, 40),
    _toggle("extensions.show_public_warning", "Показывать предупреждение о публичном JS", True)),
  _section("system.backups", "Система", "Восстановление",
    "Параметры безопасного восстановления резервной копии.",
    _toggle("backup.confirm_restore", "Подтверждать восстановление", True),
    _toggle("backup.keep_current_copy", "Сохранять копию перед восстановлением", True)),
  _section("system.diagnostics", "Система", "Системная диагностика",
    "Уровень подробности системных сообщений.",
    _select("diagnostics.detail", "Подробность", "standard", [("Кратко", "brief"), ("Стандартно", "standard"), ("Подробно", "detailed")]),
    _toggle("diagnostics.check_media", "Проверять связи изображений", True)),
  _section("system.widgets.layout", "Система", "Макет Dashboard",
    "Размер и плотность сетки виджетов.",
    _number("dashboard.card_min_width", "Минимальная ширина карточки, px", 180, 120, 360),
    _select("dashboard.mobile_layout", "Телефон", "single", [("Одна колонка", "single"), ("Две колонки", "double")])),
  _section("import.pdf.pipeline", "Импорт и экспорт", "PDF · обработка каталога",
    "Ограничения и поведение фонового импорта PDF. Секреты облака и ИИ задаются только в Anvil.",
    _number("pdf.max_file_size_mb", "Максимальный размер PDF, МБ", 50, 1, 50),
    _number("pdf.max_pages", "Максимум страниц", 2000, 1, 2000),
    _number("pdf.pages_per_batch", "Страниц за один пакет", 10, 1, 50,
            "Пакеты сохраняют checkpoint и автоматически продолжаются фоновыми задачами."),
    _number("pdf.max_products", "Товаров в одном черновике", 1000, 1, 1000),
    _toggle("pdf.ocr_enabled", "Распознавать сканированные страницы через ИИ", True),
    _toggle("pdf.auto_cloud_media", "Загружать извлечённые изображения в облако", True),
    _number("pdf.max_images", "Изображений из одного файла", 300, 1, 300),
    _number("pdf.max_image_size_mb", "Размер одного изображения, МБ", 8, 1, 8),
    _number("pdf.max_total_image_size_mb", "Общий объём изображений, МБ", 30, 1, 30),
    _number("pdf.ai_chunk_chars", "Размер текстового фрагмента ИИ", 8500, 1000, 10500),
    _toggle("pdf.retain_source_for_review", "Хранить PDF до утверждения черновика", False),
    _toggle("pdf.resume_from_checkpoint", "Возобновлять обработку с checkpoint", True)),
  _section("ai.tools.content", "ИИ · инструменты", "ИИ · сайт и контент",
    "Выберите редакторы сайта, которые будут доступны в AI Studio.",
    _toggle("ai_tool.site_rewrite", "Редактор текста сайта", True),
    _toggle("ai_tool.site_seo", "SEO-заголовки и описание", True),
    _toggle("ai_tool.site_faq", "Создание FAQ по материалу", True),
    _toggle("ai_tool.site_headline", "Заголовки и кнопки блоков", True),
    _toggle("ai_tool.site_accessibility", "Проверка доступности контента", True),
    _toggle("ai_tool.site_translate", "Черновой перевод контента", True),
    _toggle("ai_tool.site_outline", "План структуры страницы", True)),
  _section("ai.tools.catalog", "ИИ · инструменты", "ИИ · каталог и товары",
    "ИИ помогает редактировать товарные карточки и подготовить данные к проверке.",
    _toggle("ai_tool.catalog_description", "Описание карточки товара", True),
    _toggle("ai_tool.catalog_specs", "Нормализация характеристик", True),
    _toggle("ai_tool.catalog_category", "Подбор категории каталога", True),
    _toggle("ai_tool.duplicate_review", "Проверка возможных дублей", True),
    _toggle("ai_tool.catalog_import_mapping", "Сопоставление полей импорта", True),
    _toggle("ai_tool.catalog_taxonomy_review", "Проверка дерева категорий", True)),
  _section("ai.tools.operations", "ИИ · инструменты", "ИИ · заявки и инженерные работы",
    "Инструменты готовят черновики для ручной проверки сотрудником.",
    _toggle("ai_tool.order_reply", "Черновик ответа клиенту", True),
    _toggle("ai_tool.order_summary", "Сводка заявки клиента", True),
    _toggle("ai_tool.commissioning", "Чек-лист пусконаладки", True),
    _toggle("ai_tool.quote_audit", "Проверка сметы и предложения", True),
    _toggle("ai_tool.admin_settings_advice", "Помощник по настройкам проекта", True),
    _toggle("ai_tool.admin_diagnostic", "Разбор системной диагностики", True),
    _toggle("ai_tool.pdf_import_triage", "Разбор ошибок импорта PDF", True))
,
  _section("design.visual.system", "Дизайн", "Visual Design System",
    "Центральное управление визуальным языком всего продукта.",
    _select("design.visual.preset", "Визуальный характер", "engineering", [("Engineering Premium", "engineering"), ("Industrial Pro", "industrial"), ("Luxury Minimal", "luxury"), ("Technical Dark", "technical")]),
    _select("design.visual.radius", "Радиус интерфейса", "medium", [("Sharp", "sharp"), ("Compact", "compact"), ("Medium", "medium"), ("Soft", "soft")]),
    _select("design.visual.depth", "Глубина поверхностей", "premium", [("Flat", "flat"), ("Balanced", "balanced"), ("Premium", "premium")]),
    _toggle("design.visual.micro_details", "Инженерные микроэлементы", True),
    _toggle("design.visual.glow", "Акцентное свечение", True)),
  _section("design.layout", "Дизайн", "Layout Studio",
    "Управление сеткой, шириной контента и плотностью страниц.",
    _number("design.layout.max_width", "Максимальная ширина, px", 1440, 960, 2200),
    _number("design.layout.page_gap", "Межсекционный интервал, px", 32, 8, 100),
    _select("design.layout.grid", "Сетка", "12", [("8 колонок", "8"), ("12 колонок", "12"), ("16 колонок", "16")]),
    _toggle("design.layout.full_bleed", "Разрешить full-width блоки", True),
    _toggle("design.layout.sticky_actions", "Закреплять основные действия", True)),
  _section("design.components", "Дизайн", "Component Studio",
    "Единые правила кнопок, карточек, таблиц, badges и состояний.",
    _select("design.components.buttons", "Стиль кнопок", "premium", [("Minimal", "minimal"), ("Premium", "premium"), ("Industrial", "industrial")]),
    _select("design.components.cards", "Стиль карточек", "elevated", [("Flat", "flat"), ("Elevated", "elevated"), ("Glass", "glass")]),
    _select("design.components.badges", "Стиль статусов", "solid", [("Outline", "outline"), ("Soft", "soft"), ("Solid", "solid")]),
    _toggle("design.components.hover_lift", "Подъём карточек при наведении", True),
    _toggle("design.components.image_zoom", "Увеличение изображений", True)),
  _section("design.hero", "Дизайн", "Hero & Landing Studio",
    "Редактор поведения первых экранов и промо-секций.",
    _select("design.hero.layout", "Композиция Hero", "split", [("Split", "split"), ("Centered", "centered"), ("Asymmetric", "asymmetric")]),
    _select("design.hero.visual", "Визуальный режим", "engineering", [("Engineering", "engineering"), ("Editorial", "editorial"), ("Minimal", "minimal")]),
    _toggle("design.hero.show_metrics", "Показывать ключевые показатели", True),
    _toggle("design.hero.show_grid", "Показывать инженерную сетку", True),
    _toggle("design.hero.parallax", "Лёгкий parallax", False)),
  _section("design.motion", "Дизайн", "Motion Studio",
    "Единая система анимаций и переходов.",
    _select("design.motion.level", "Интенсивность", "medium", [("Off", "off"), ("Subtle", "subtle"), ("Medium", "medium"), ("Cinematic", "cinematic")]),
    _select("design.motion.page_transition", "Переход страниц", "fade-up", [("None", "none"), ("Fade", "fade"), ("Fade Up", "fade-up"), ("Scale", "scale")]),
    _number("design.motion.duration", "Базовая длительность, ms", 280, 80, 900),
    _toggle("design.motion.stagger", "Последовательная анимация сеток", True),
    _toggle("design.motion.reduced_motion", "Уважать reduced-motion", True)),
  _section("design.mobile", "Дизайн", "Mobile Experience",
    "Отдельные правила мобильного интерфейса.",
    _select("design.mobile.navigation", "Мобильная навигация", "drawer", [("Drawer", "drawer"), ("Bottom Bar", "bottom"), ("Compact Header", "header")]),
    _select("design.mobile.cards", "Карточки на мобильном", "single", [("1 колонка", "single"), ("2 колонки", "double")]),
    _toggle("design.mobile.compact_tables", "Компактные таблицы", True),
    _toggle("design.mobile.sticky_cta", "Закреплённый CTA", True)),
  _section("content.visual-editor", "Контент", "Visual Page Builder",
    "Расширенный конструктор контентных секций.",
    _toggle("content.builder.sections", "Разрешить секции", True),
    _toggle("content.builder.reorder", "Перетаскивание секций", True),
    _toggle("content.builder.preview", "Live Preview", True),
    _toggle("content.builder.duplicate", "Дублирование блоков", True),
    _toggle("content.builder.templates", "Шаблоны блоков", True)),
  _section("seo.advanced", "SEO", "SEO Control Center",
    "Расширенное управление поисковой оптимизацией.",
    _toggle("seo.advanced.schema", "Structured Data", True),
    _toggle("seo.advanced.breadcrumbs", "Breadcrumb Schema", True),
    _toggle("seo.advanced.sitemap", "Автоматическая карта сайта", True),
    _toggle("seo.advanced.canonical", "Автоматические canonical", True),
    _toggle("seo.advanced.noindex_drafts", "Noindex для черновиков", True)),
  _section("performance.control", "Система", "Performance Control",
    "Управление скоростью и загрузкой ресурсов.",
    _toggle("performance.lazy_images", "Lazy Load изображений", True),
    _toggle("performance.webp", "Предпочитать WebP", True),
    _toggle("performance.preload_hero", "Preload главного изображения", True),
    _toggle("performance.minimize_motion", "Уменьшать motion на слабых устройствах", True),
    _number("performance.image_quality", "Качество изображений, %", 84, 50, 100)),
  _section("security.control", "Безопасность", "Security Control Center",
    "Центральные политики безопасности.",
    _toggle("security.require_2fa", "Требовать 2FA для администраторов", False),
    _toggle("security.session_limit", "Ограничивать длительность сессии", True),
    _number("security.session_hours", "Сессия, часов", 12, 1, 168),
    _toggle("security.audit_sensitive", "Расширенный аудит", True),
    _toggle("security.block_repeated_failures", "Защита от повторных попыток входа", True)),
  _section("workflow.automation", "Рабочие процессы", "Workflow Automation",
    "Автоматизация типовых операций команды.",
    _toggle("workflow.auto_assign", "Автоматически назначать ответственного", False),
    _toggle("workflow.order_notifications", "Автоуведомления по заявкам", True),
    _toggle("workflow.task_reminders", "Напоминания по задачам", True),
    _toggle("workflow.status_history", "История изменения статусов", True)),
  _section("dashboard.pro", "Dashboard", "Command Center Dashboard",
    "Профессиональный рабочий стол администратора.",
    _select("dashboard.pro.density", "Плотность Dashboard", "dense", [("Compact", "compact"), ("Balanced", "balanced"), ("Dense", "dense")]),
    _toggle("dashboard.pro.kpi", "KPI-панели", True),
    _toggle("dashboard.pro.activity", "Лента активности", True),
    _toggle("dashboard.pro.health", "System Health", True),
    _toggle("dashboard.pro.quick_actions", "Быстрые действия", True),
    _toggle("dashboard.pro.realtime", "Realtime-индикаторы", True)),
  _section("system.diagnostics.pro", "Система", "Advanced Diagnostics",
    "Глубокая диагностика приложения.",
    _toggle("diagnostics.runtime", "Проверять runtime", True),
    _toggle("diagnostics.data_integrity", "Проверять целостность данных", True),
    _toggle("diagnostics.catalog", "Проверять каталог", True),
    _toggle("diagnostics.images", "Проверять изображения", True),
    _toggle("diagnostics.calculators", "Проверять калькуляторы", True),
    _toggle("diagnostics.links", "Проверять внутренние ссылки", True)),
  _section("admin.workspace", "Система", "Admin Workspace",
    "Персонализация рабочего пространства администратора.",
    _select("admin.workspace.theme", "Тема панели", "inherit", [("Как сайт", "inherit"), ("Graphite", "graphite"), ("Arctic", "arctic"), ("Titanium", "titanium")]),
    _select("admin.workspace.sidebar", "Sidebar", "expanded", [("Expanded", "expanded"), ("Compact", "compact"), ("Auto", "auto")]),
    _toggle("admin.workspace.command_palette", "Command Palette", True),
    _toggle("admin.workspace.keyboard_shortcuts", "Горячие клавиши", True),
    _toggle("admin.workspace.breadcrumbs", "Breadcrumbs", True)),
  _section("admin.branding", "Система", "Admin Branding",
    "Фирменное оформление Control Center.",
    _text("admin.branding.title", "Название панели", "КЛИМАЭКО CONTROL CENTER", maximum=80),
    _text("admin.branding.subtitle", "Подзаголовок", "ENGINEERING MANAGEMENT PLATFORM", maximum=120),
    _toggle("admin.branding.status", "Показывать System Status", True),
    _toggle("admin.branding.version", "Показывать версию", True)),
